### ISSUE TITLE
set-ui-spec! doesn't work with nested CSS maps

### ISSUE THREAD

**Issue by hlship** [AvisoNovate/taxi-toolkit#10] opened 2015-06-17 18:43 UTC
I'm trying to define a top-level element that contains nested sub-elements. I'm identifying the sub-elements using css.

In the process of invoking set-ui-spec!, the nested maps (from by-css) are being converted to a useless string:

```
(set-ui-spec! {:outer [(by-css ".outer")
                       :inner (by-css ".inner")]})
=> {:outer {:inner "[:css \".inner\"]", :self {:css ".outer"}}}
```

This prevents any match on the inner element.

This may be the same as #5.

It looks like $ (and find-one or find-all) are really keyed into xpath, with the idea that child elements can be found by appending the xpath strings together.

I think a better approach would be to use find-element for the outer element, then switch to find-element-under on the initial result and the 2nd ui-map key.

**Comment by hlship** [comment] 2015-06-17 18:52
Ok, so what it really looks like is that CSS is not supported anywhere inside set-ui-spec!.

**Comment by kamituel** [comment] 2015-07-06 14:12
Hi Howard,
this indeed a duplicate of #5. We're working on a fix in there, so I'll close this issue for now.
Thanks for reporting!

**Closed as completed by kamituel** 2015-07-06 14:12 UTC
